project:
  type: website

website:
  title: "GIS Project"
  navbar:
    left:
      - href: overview.html
        text: Overview
      - href: methodology.qmd
        text: Methodology
      - href: Analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Results and Discussion
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
